version: '3.6'

networks:
  rocktreff: {}

services:
  # dhcpd
  dhcpd:
    container_name: dhcpd
    image: networkboot/dhcpd:latest
    network_mode: host
    restart: always
    volumes:
      - ./dhcpd:/data

  # pihole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 1337:80/tcp
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: 13nimda37
      VIRTUAL_HOST: pihole.local.rocktreff.de
    labels:
      - traefik.frontend.rule=Host:pihole.local.rocktreff.de
      - traefik.port=80
    volumes:
      - ./pihole/etc/pihole:/etc/pihole/
      - ./pihole/etc/dnsmasq.d:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      - rocktreff
    extra_hosts:
      - monitor.local.rocktreff.de:10.13.38.23
      - dashboard.local.rocktreff.de:10.13.38.23
      - pihole.local.rocktreff.de:10.13.38.23
      - unifi.local.rocktreff.de:10.13.38.23
