version: '3.6'

networks:
  rocktreff:

volumes:
  db: {}
  data: {}
  log: {}
  cert: {}
  init: {}

services:

  # mongodb
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    networks:
      - rocktreff
    volumes:
      - db:/data/db

  # unifi
  unifi:
    container_name: unifi
    image: jacobalberty/unifi:v7
    restart: always
    depends_on:
      - mongodb
    networks:
      - rocktreff
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongodb/unifi
      STATDB_URI: mongodb://mongodb/unifi_stat
      DB_NAME: unifi
      TZ: Europe/Berlin
    labels:
      - traefik.frontend.rule=Host:unifi.local.rocktreff.de
      - traefik.port=8443
      - traefik.protocol=https
    ports:
      - ${HOST_IP}:161:161 # SNMP
      - 3478:3478/udp # STUN
      - 6789:6789/tcp # Speed test
      - 8080:8080/tcp # Device/ controller comm.
      - 8443:8443/tcp # Controller GUI/API as seen in a web browser
      - 8843:8843/tcp # HTTPS portal redirection
      - 10001:10001/udp # AP discovery
