version: '3.6'

networks:
  monitoring:
  proxy:

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  # prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.10.0
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    labels:
      - traefik.frontend.rule=Host:prometheus.local.rocktreff.de
      - traefik.port=9090
    depends_on:
      - traefik
      - cadvisor
    networks:
      - monitoring
      - proxy

  # node exporter
  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - monitoring

  # alertmanager
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    restart: always
    volumes:
      - ./alertmanager:/etc/alertmanager
    networks:
      - monitoring
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  # cAdvisor
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --allow_dynamic_housekeeping=true
      - --housekeeping_interval=30s
      - --global_housekeeping_interval=2m
      - --disable_metrics=disk,tcp,udp
    networks:
      - monitoring

  # SNMP Exporter
  snmp_exporter:
    container_name: snmp_exporter
    image: prom/snmp-exporter
    restart: always
    networks:
      - monitoring

  # Blackbox Exporter
  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:master
    restart: always
    networks:
      - monitoring

  # grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:6.2.1
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/env.config.monitoring
    labels:
      - traefik.frontend.rule=Host:dashboard.local.rocktreff.de
      - traefik.port=3000
    depends_on:
      - traefik
    networks:
      - monitoring
      - proxy

