debug = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/fullchain.pem"
      keyFile = "/certs/privkey.pem"

[api]

[web]
address = ":8080"

[docker]
domain = "local.rocktreff.de"
watch = true
network = "proxy"
