{
 "title": "RT 2019",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sendemast",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*irate(ifHCInOctets{instance=\"172.23.0.1\",ifName=\"eth0\"}[1m])",
     "legendFormat": "Downstream"
    },
    {
     "expr": "8*irate(ifHCOutOctets{instance=\"172.23.0.1\",ifName=\"eth0\"}[1m])",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "FOH/Stage Primary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.12\",ifName=\"0/49\"}[1m])*8 + irate(ifHCOutOctets{instance=\"172.23.0.12\",ifName=\"0/49\"}[1m])*8",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "FOH/Stage Secondary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.13\",ifName=\"0/26\"}[1m])*8 + irate(ifHCOutOctets{instance=\"172.23.0.13\",ifName=\"0/26\"}[1m])*8",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Stage/Amptown Primary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.11\",ifName=\"0/49\"}[1m])*8 + irate(ifHCOutOctets{instance=\"172.23.0.11\",ifName=\"0/49\"}[1m])*8",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Stage/Amptown Secondary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.11\",ifName=\"0/49\"}[1m])*8 + irate(ifHCOutOctets{instance=\"172.23.0.11\",ifName=\"0/49\"}[1m])*8",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.1\",ifName=\"eth0\"}[1m])*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Upload ALEX BERLIN",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.1\",ifName=\"eth7.17\"}[1m])*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Upload ROCKTREFF",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.1\",ifName=\"eth7.11\"}[1m])*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Upload ROCKINI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"172.23.0.1\",ifName=\"eth7.10\"}[1m])*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Noise per AP",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(unifi_stations_noise_dbm) by (ap_mac)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Wifi User",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(unifi_devices_stations_user)"
    }
   ]
  },
  {
   "title": "Wifi User by Radio",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(unifi_devices_stations_user) by (radio)",
     "legendFormat": "{{radio}}"
    }
   ]
  },
  {
   "title": "Errors Primary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"172.23.0.14\",ifName=\"0/49\"}[30s]) + rate(ifOutErrors{instance=\"172.23.0.14\",ifName=\"0/49\"}[30s])",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Errors Secondary",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"172.23.0.13\",ifName=\"0/26\"}[30s]) + rate(ifOutErrors{instance=\"172.23.0.13\",ifName=\"0/26\"}[30s])",
     "legendFormat": "in"
    }
   ]
  }
 ]
}